//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDB_First
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSVEntities : DbContext
    {
        public QLSVEntities()
            : base("name=QLSVEntities") // do chuoi ket noi dat ten là QLSVEntities; tuong trung cho csdl  ; tim trong file app.config chuoi ket noi la
            //QLSVEntities -> về  csdl tương ứng với connection string lấy các record của các table khỏi tạo cho list các đối tượng của các class tương ứng
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LopSH> LopSHes { get; set; }
        public virtual DbSet<SV> SVs { get; set; }
    }
}
